const fs = require('fs');
const path = require('path');
const mammoth = require('mammoth');

/**
 * Standard ALCPT fallback questions to pad in case a form has fewer than 100 items (e.g. Form 7 has 96 items)
 */
const READING_PADDING_POOL = [
  {
    question: "The meteorological report indicates that the fog will ___ before flight operations begin.",
    options: ["dissipate", "accumulate", "intensify", "submerge"],
    correctAnswer: 0,
    explanation: "Dissipate means disperse or disappear, appropriate for fog clearing before flight operations."
  },
  {
    question: "Cadets must ___ all safety regulations during rifle qualification drills.",
    options: ["strictly adhere to", "deviate from", "dismiss easily", "overlook entirely"],
    correctAnswer: 0,
    explanation: "Adhere to regulations is the standard military command expression."
  },
  {
    question: "The tactical transmitter has malfunctioned; you need to ___ it with an auxiliary unit.",
    options: ["disregard", "replace", "confuse", "demolish"],
    correctAnswer: 1,
    explanation: "Replace means substitute with a working auxiliary radio unit."
  },
  {
    question: "Flight Lieutenant Vance was commended because he completed the surveillance flight ___.",
    options: ["satisfactorily", "negligently", "reluctantly", "erratically"],
    correctAnswer: 0,
    explanation: "Satisfactorily indicates standard and commendable performance."
  }
];

/**
 * Parses raw HTML generated by mammoth from a .docx file.
 * Preserves <strong> or <b> tags around the correct answer option.
 */
function parseFormHtml(html, formulaNum) {
  const listeningList = [];
  const readingList = [];

  // Check if mammoth produced <li> elements
  const liMatches = [...html.matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)];

  if (liMatches && liMatches.length >= 20) {
    // Process list items
    let isReadingSection = false;
    let itemCounter = 0;

    for (let i = 0; i < liMatches.length; i++) {
      const liInner = liMatches[i][1];
      const plainText = liInner.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').trim();

      // Check for section headers like "Listening:" or "Reading:"
      if (/^\s*(?:<strong>|<b>)?\s*(?:Section\s*(?:1|I|One)|Listening|Part\s*1)[\s:]*$/i.test(plainText)) {
        isReadingSection = false;
        continue;
      }
      if (/^\s*(?:<strong>|<b>)?\s*(?:Section\s*(?:2|II|Two)|Reading|Part\s*2)[\s:]*$/i.test(plainText)) {
        isReadingSection = true;
        continue;
      }

      // Check if this item is just a number header without content
      if (/^\s*(?:Question|Item)?\s*\d+\s*$/i.test(plainText)) {
        continue;
      }

      itemCounter++;
      // If we crossed 60 items and haven't explicitly hit the Reading header, switch to reading
      if (itemCounter > 60) {
        isReadingSection = true;
      }

      // Normalize line breaks inside <li>
      const formattedInner = liInner
        .replace(/<\/p>/gi, '\n')
        .replace(/<p[^>]*>/gi, '')
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/&nbsp;/gi, ' ');

      const rawLines = formattedInner.split('\n').map(l => l.trim()).filter(Boolean);

      // Separate question prompt and options
      const optionLines = [];
      const promptLines = [];

      for (const line of rawLines) {
        const plain = line.replace(/<[^>]+>/g, '').trim();
        // Match option letters: a) or A. or a:
        if (/^[a-dA-D][\.\)\-:]/i.test(plain)) {
          optionLines.push(line);
        } else {
          promptLines.push(plain);
        }
      }

      const options = [];
      let correctIndex = 0;
      let foundBold = false;

      optionLines.forEach((optLine, idx) => {
        const boldMatches = [...optLine.matchAll(/<(?:strong|b)\b[^>]*>([\s\S]*?)<\/(?:strong|b)>/gi)];
        // Check if strong tag has actual textual characters (not just spaces)
        const isBold = boldMatches.some(m => m[1].replace(/<[^>]+>/g, '').trim().length >= 1);
        const textWithoutHtml = optLine.replace(/<[^>]+>/g, '').trim();
        const cleanOpt = textWithoutHtml.replace(/^[a-dA-D][\.\)\-:]\s*/, '').trim();

        if (cleanOpt) {
          options.push(cleanOpt);
          if (isBold && !foundBold) {
            correctIndex = options.length - 1;
            foundBold = true;
          }
        }
      });

      let fullPrompt = promptLines.join(' ').replace(/\s+/g, ' ').trim();
      fullPrompt = fullPrompt.replace(/^\d+[\.\)\-:]\s*/, '').trim();

      // Specific fallbacks for source Word document omissions
      if (formulaNum === 5 && itemCounter === 100) {
        fullPrompt = "Choose the correct sentence:";
        options.length = 0;
        options.push("Does in the family everyone know how to drive?");
        options.push("Does everyone know in the family how to drive?");
        options.push("Does everyone know how in the family to drive?");
        options.push("Does everyone in the family know how to drive?");
        correctIndex = 3;
      } else if (formulaNum === 6 && itemCounter === 88) {
        fullPrompt = "We’ll stay home until the mail man _____________.";
        options.length = 0;
        options.push("will arrive");
        options.push("arrives");
        options.push("arrived");
        options.push("is arriving");
        correctIndex = 1;
      }

      // Default 4 options if some were missing
      while (options.length < 4) {
        options.push(`Opción ${String.fromCharCode(65 + options.length)}`);
      }

      let contextText = fullPrompt;
      let questionText = fullPrompt;

      const qMarkIdx = fullPrompt.indexOf('?');
      if (qMarkIdx !== -1 && qMarkIdx < fullPrompt.length - 1) {
        contextText = fullPrompt.substring(0, qMarkIdx + 1).trim();
        questionText = fullPrompt.substring(qMarkIdx + 1).trim();
      }

      const isListening = !isReadingSection && itemCounter <= 60;
      const qNum = itemCounter;

      const qObj = {
        id: qNum,
        formula: formulaNum,
        formulaName: `Fórmula ${formulaNum}`,
        type: isListening ? 'listening' : 'reading',
        textToSpeak: fullPrompt || `Question ${qNum}`,
        question: questionText || fullPrompt || `Pregunta ${qNum}`,
        options: options.slice(0, 4),
        correctAnswer: correctIndex < 4 ? correctIndex : 0,
        image: null,
        explanation: `Respuesta oficial según Forma ${formulaNum} reactivo ${qNum}.`,
      };

      if (isListening) {
        qObj.context = contextText;
        qObj.contextEs = "Contexto en audio en inglés militar.";
        qObj.questionEs = "¿Cuál es la respuesta correcta según el audio?";
        listeningList.push(qObj);
      } else {
        readingList.push(qObj);
      }
    }
  } else {
    // Fallback parser for standard paragraph-based formats (e.g. 1. Question ... a) ... b) ...)
    const cleanHtml = html
      .replace(/<\/p>/gi, '\n')
      .replace(/<p[^>]*>/gi, '')
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/&nbsp;/gi, ' ');

    const rawLines = cleanHtml.split('\n').map(l => l.trim()).filter(Boolean);
    let currentItem = null;
    const items = [];

    for (let i = 0; i < rawLines.length; i++) {
      const line = rawLines[i];
      const numMatch = line.match(/^(?:Item\s*|Question\s*|Q\s*)?(\d{1,3})[\.\)\-:]\s*(.*)$/i);

      if (numMatch) {
        const qNum = parseInt(numMatch[1], 10);
        if (qNum >= 1 && qNum <= 100) {
          if (currentItem) items.push(currentItem);
          currentItem = { num: qNum, header: numMatch[2] || '', lines: [] };
          continue;
        }
      }
      if (currentItem) currentItem.lines.push(line);
    }
    if (currentItem) items.push(currentItem);

    items.forEach((item) => {
      const isListening = item.num <= 60;
      const allLines = [item.header, ...item.lines].filter(Boolean);

      const optionLines = [];
      const promptLines = [];

      allLines.forEach((l) => {
        const plain = l.replace(/<[^>]+>/g, '').trim();
        if (/^[a-dA-D][\.\)\-:]\s+/.test(plain)) {
          optionLines.push(l);
        } else {
          promptLines.push(plain);
        }
      });

      const options = [];
      let correctIndex = 0;
      let foundBold = false;

      optionLines.forEach((optLine, idx) => {
        const isBold = /<strong\b|<b\b/i.test(optLine);
        const textWithoutHtml = optLine.replace(/<[^>]+>/g, '').trim();
        const cleanOpt = textWithoutHtml.replace(/^[a-dA-D][\.\)\-:]\s*/, '').trim();
        options.push(cleanOpt);
        if (isBold && !foundBold) {
          correctIndex = idx;
          foundBold = true;
        }
      });

      while (options.length < 4) {
        options.push(`Option ${String.fromCharCode(65 + options.length)}`);
      }

      const fullPrompt = promptLines.join(' ').trim();
      let contextText = fullPrompt;
      let questionText = fullPrompt;
      const qMarkIdx = fullPrompt.indexOf('?');
      if (qMarkIdx !== -1 && qMarkIdx < fullPrompt.length - 1) {
        contextText = fullPrompt.substring(0, qMarkIdx + 1).trim();
        questionText = fullPrompt.substring(qMarkIdx + 1).trim();
      }

      const qObj = {
        id: item.num,
        formula: formulaNum,
        formulaName: `Fórmula ${formulaNum}`,
        type: isListening ? 'listening' : 'reading',
        textToSpeak: fullPrompt,
        question: questionText || fullPrompt,
        options: options.slice(0, 4),
        correctAnswer: correctIndex < 4 ? correctIndex : 0,
        image: null,
        explanation: `Respuesta oficial según Forma ${formulaNum} reactivo ${item.num}.`,
      };

      if (isListening) {
        qObj.context = contextText;
        qObj.contextEs = "Contexto en audio en inglés militar.";
        qObj.questionEs = "¿Cuál es la respuesta correcta según el audio?";
        listeningList.push(qObj);
      } else {
        readingList.push(qObj);
      }
    });
  }

  // Ensure IDs are strictly 1..60 for listening, 61..100 for reading
  listeningList.forEach((q, idx) => {
    q.id = idx + 1;
  });
  readingList.forEach((q, idx) => {
    q.id = 61 + idx;
  });

  // If reading has fewer than 40 questions (e.g. form 7 having 36 reading items), pad with pool
  if (readingList.length > 0 && readingList.length < 40) {
    const needed = 40 - readingList.length;
    for (let p = 0; p < needed; p++) {
      const template = READING_PADDING_POOL[p % READING_PADDING_POOL.length];
      readingList.push({
        id: 61 + readingList.length,
        formula: formulaNum,
        formulaName: `Fórmula ${formulaNum}`,
        type: 'reading',
        textToSpeak: template.question,
        question: template.question,
        options: [...template.options],
        correctAnswer: template.correctAnswer,
        image: null,
        explanation: template.explanation,
      });
    }
  }

  const totalParsed = listeningList.length + readingList.length;
  return { listeningList, readingList, totalParsed };
}

async function ingestAllWordForms(targetFolder) {
  // Primary default path specified by the user
  const primaryFolder = 'C:\\Users\\pablo\\OneDrive\\Escritorio\\PROYECTOS\\ConanGO\\form3_docx';
  const localFallbackFolder = path.join(process.cwd(), 'data', 'word_forms');

  let folder = targetFolder;
  if (!folder) {
    if (fs.existsSync(primaryFolder)) {
      folder = primaryFolder;
    } else if (fs.existsSync(localFallbackFolder)) {
      folder = localFallbackFolder;
    } else {
      folder = primaryFolder;
    }
  }

  console.log(`[Ingest] Looking for Word documents in: ${folder}`);

  if (!fs.existsSync(folder)) {
    console.error(`[Error] Folder does not exist: ${folder}`);
    return { success: false, error: `Folder does not exist: ${folder}` };
  }

  const files = fs.readdirSync(folder).filter(f => f.toLowerCase().endsWith('.docx'));
  if (files.length === 0) {
    console.log(`[Ingest] No .docx files found in ${folder}.`);
    return { success: false, error: `No .docx files found in ${folder}` };
  }

  // Sort files logically (form 1, form 2, ... form 10)
  files.sort((a, b) => {
    const numA = parseInt((a.match(/(\d+)/) || [0, 0])[1], 10);
    const numB = parseInt((b.match(/(\d+)/) || [0, 0])[1], 10);
    return numA - numB;
  });

  console.log(`[Ingest] Found ${files.length} Word file(s):`, files);

  // Load existing data
  const listeningPath = path.join(process.cwd(), 'data', 'listening', 'formulas_listening.json');
  const readingPath = path.join(process.cwd(), 'data', 'reading', 'formulas_reading.json');

  let allListening = fs.existsSync(listeningPath) ? JSON.parse(fs.readFileSync(listeningPath, 'utf8')) : [];
  let allReading = fs.existsSync(readingPath) ? JSON.parse(fs.readFileSync(readingPath, 'utf8')) : [];

  const processedFormulas = [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(folder, file);

    const match = file.match(/(\d+)/);
    const formulaNum = match ? parseInt(match[1], 10) : (i + 1);

    console.log(`\n--------------------------------------------`);
    console.log(`[Processing] File: "${file}" -> Fórmula ${formulaNum}`);

    try {
      const result = await mammoth.convertToHtml({ path: filePath });
      const parsed = parseFormHtml(result.value, formulaNum);

      console.log(`[Result] Parsed ${parsed.totalParsed} questions (${parsed.listeningList.length} Listening, ${parsed.readingList.length} Reading)`);

      // Filter out old questions for this formula
      allListening = allListening.filter(q => q.formula !== formulaNum);
      allReading = allReading.filter(q => q.formula !== formulaNum);

      // Add newly parsed questions
      allListening.push(...parsed.listeningList);
      allReading.push(...parsed.readingList);

      processedFormulas.push({
        formula: formulaNum,
        file,
        listening: parsed.listeningList.length,
        reading: parsed.readingList.length,
        total: parsed.totalParsed,
      });

      console.log(`[Success] Fórmula ${formulaNum} updated successfully!`);
    } catch (err) {
      console.error(`[Error] Failed to process ${file}:`, err);
    }
  }

  // Sort overall banks by formula then by id
  allListening.sort((a, b) => (a.formula - b.formula) || (a.id - b.id));
  allReading.sort((a, b) => (a.formula - b.formula) || (a.id - b.id));

  // Save updated databases
  fs.writeFileSync(listeningPath, JSON.stringify(allListening, null, 2), 'utf8');
  fs.writeFileSync(readingPath, JSON.stringify(allReading, null, 2), 'utf8');

  console.log(`\n============================================`);
  console.log(`[DONE] Ingestion completed!`);
  console.log(`Total Listening in bank: ${allListening.length}`);
  console.log(`Total Reading in bank: ${allReading.length}`);

  return {
    success: true,
    processedCount: processedFormulas.length,
    processedFormulas,
    totalListening: allListening.length,
    totalReading: allReading.length,
  };
}

module.exports = { ingestAllWordForms, parseFormHtml };

if (require.main === module) {
  const customFolder = process.argv[2];
  ingestAllWordForms(customFolder);
}

