const fs = require('fs');
const path = require('path');
const mammoth = require('mammoth');

/**
 * Parses raw HTML generated by mammoth from a .docx file.
 * Preserves <strong> or <b> tags around the correct answer option.
 */
function parseFormHtml(html, formulaNum) {
  // Normalize paragraph breaks
  const cleanHtml = html
    .replace(/<\/p>/gi, '\n')
    .replace(/<p[^>]*>/gi, '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/&nbsp;/gi, ' ');

  const rawLines = cleanHtml.split('\n').map(l => l.trim()).filter(Boolean);
  
  const listeningList = [];
  const readingList = [];
  
  // A question typically starts with a number like "1.", "1 -", "Item 1", "Question 1", or similar
  let currentItem = null;
  const items = [];

  for (let i = 0; i < rawLines.length; i++) {
    const line = rawLines[i];
    
    // Check if line starts with an item number like: "1.", "1)", "Item 1:", "Q1.", "1 -"
    const numMatch = line.match(/^(?:Item\s*|Question\s*|Q\s*)?(\d{1,3})[\.\)\-:]\s*(.*)$/i);
    
    if (numMatch) {
      const qNum = parseInt(numMatch[1], 10);
      // Valid ALCPT numbers are 1 to 100
      if (qNum >= 1 && qNum <= 100) {
        if (currentItem) {
          items.push(currentItem);
        }
        currentItem = {
          num: qNum,
          header: numMatch[2] || '',
          lines: [],
        };
        continue;
      }
    }

    if (currentItem) {
      currentItem.lines.push(line);
    }
  }

  if (currentItem) {
    items.push(currentItem);
  }

  // Helper to extract option text and detect if it has strong/b
  function parseOptionLine(line) {
    const isBold = /<strong\b|<b\b/i.test(line);
    // Strip HTML tags for clean text
    const textWithoutHtml = line.replace(/<[^>]+>/g, '').trim();
    // Strip leading a), b), c), d), A., B., etc.
    const cleanOpt = textWithoutHtml.replace(/^[a-dA-D][\.\)\-:]\s*/, '').trim();
    return { text: cleanOpt, isBold };
  }

  items.forEach((item) => {
    const isListening = item.num <= 60;
    const allLines = [item.header, ...item.lines].filter(Boolean);

    // Identify option lines: lines starting with a), b), c), d) or matching pattern
    const optionLines = [];
    const promptLines = [];

    allLines.forEach((l) => {
      const plain = l.replace(/<[^>]+>/g, '').trim();
      if (/^[a-dA-D][\.\)\-:]\s+/.test(plain)) {
        optionLines.push(l);
      } else {
        promptLines.push(plain);
      }
    });

    const options = [];
    let correctIndex = 0;
    let foundBold = false;

    optionLines.forEach((optLine, idx) => {
      const parsed = parseOptionLine(optLine);
      options.push(parsed.text);
      if (parsed.isBold && !foundBold) {
        correctIndex = idx;
        foundBold = true;
      }
    });

    // Fallback if options couldn't be cleanly parsed
    while (options.length < 4) {
      options.push(`Option ${String.fromCharCode(65 + options.length)}`);
    }

    const fullPrompt = promptLines.join(' ').trim();
    
    // For listening, split context / situation vs actual question if applicable
    let contextText = fullPrompt;
    let questionText = fullPrompt;
    
    const qMarkIdx = fullPrompt.indexOf('?');
    if (qMarkIdx !== -1 && qMarkIdx < fullPrompt.length - 1) {
      contextText = fullPrompt.substring(0, qMarkIdx + 1).trim();
      questionText = fullPrompt.substring(qMarkIdx + 1).trim();
    }

    const qObj = {
      id: item.num,
      formula: formulaNum,
      formulaName: `Fórmula ${formulaNum}`,
      type: isListening ? 'listening' : 'reading',
      textToSpeak: fullPrompt,
      question: questionText || fullPrompt,
      options: options.slice(0, 4),
      correctAnswer: correctIndex,
      image: null,
      explanation: `Respuesta oficial según Forma ${formulaNum} reactivo ${item.num}.`,
    };

    if (isListening) {
      qObj.context = contextText;
      qObj.contextEs = "Contexto en audio en inglés militar.";
      qObj.questionEs = "¿Cuál es la respuesta correcta según el audio?";
      listeningList.push(qObj);
    } else {
      readingList.push(qObj);
    }
  });

  return { listeningList, readingList, totalParsed: items.length };
}

async function ingestAllWordForms(targetFolder) {
  const folder = targetFolder || path.join(process.cwd(), 'data', 'word_forms');
  console.log(`[Ingest] Looking for Word documents in: ${folder}`);
  
  if (!fs.existsSync(folder)) {
    console.error(`[Error] Folder does not exist: ${folder}`);
    return;
  }

  const files = fs.readdirSync(folder).filter(f => f.toLowerCase().endsWith('.docx'));
  if (files.length === 0) {
    console.log(`[Ingest] No .docx files found in ${folder}.`);
    console.log(`Please place your 8 Word files in: ${folder}`);
    return;
  }

  console.log(`[Ingest] Found ${files.length} Word file(s):`, files);

  // Load existing data
  const listeningPath = path.join(process.cwd(), 'data', 'listening', 'formulas_listening.json');
  const readingPath = path.join(process.cwd(), 'data', 'reading', 'formulas_reading.json');

  let allListening = fs.existsSync(listeningPath) ? JSON.parse(fs.readFileSync(listeningPath, 'utf8')) : [];
  let allReading = fs.existsSync(readingPath) ? JSON.parse(fs.readFileSync(readingPath, 'utf8')) : [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(folder, file);

    // Extract formula number from filename (e.g. "Forma 1", "Form 2", "Forma_03", or index + 1)
    const match = file.match(/(\d+)/);
    const formulaNum = match ? parseInt(match[1], 10) : (i + 1);

    console.log(`\n--------------------------------------------`);
    console.log(`[Processing] File: "${file}" -> Fórmula ${formulaNum}`);

    try {
      const result = await mammoth.convertToHtml({ path: filePath });
      const parsed = parseFormHtml(result.value, formulaNum);

      console.log(`[Result] Parsed ${parsed.totalParsed} questions (${parsed.listeningList.length} Listening, ${parsed.readingList.length} Reading)`);

      // Filter out old questions for this formula
      allListening = allListening.filter(q => q.formula !== formulaNum);
      allReading = allReading.filter(q => q.formula !== formulaNum);

      // Add newly parsed questions
      allListening.push(...parsed.listeningList);
      allReading.push(...parsed.readingList);

      console.log(`[Success] Fórmula ${formulaNum} updated successfully!`);
    } catch (err) {
      console.error(`[Error] Failed to process ${file}:`, err);
    }
  }

  // Save updated databases
  fs.writeFileSync(listeningPath, JSON.stringify(allListening, null, 2), 'utf8');
  fs.writeFileSync(readingPath, JSON.stringify(allReading, null, 2), 'utf8');

  console.log(`\n============================================`);
  console.log(`[DONE] Ingestion completed!`);
  console.log(`Total Listening in bank: ${allListening.length}`);
  console.log(`Total Reading in bank: ${allReading.length}`);
}

module.exports = { ingestAllWordForms, parseFormHtml };

if (require.main === module) {
  const customFolder = process.argv[2];
  ingestAllWordForms(customFolder);
}
